/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cabinetmedical;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author HP
 */
public class FichePatient extends javax.swing.JFrame {
Connection c;
    /**
     * Creates new form FichePatient
     */
    public FichePatient() {
        initComponents();
          this.setLocationRelativeTo(null);
          this.setTitle("Fiche_Patient");
          try {
              
            //étape 1: charger la classe de driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            //étape 2: créer l'objet de connexion
            c = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/Cabinet_medicale", "root", "");
             
             // System.out.println(MEDICAL.idMed);
          // afficherRDV();
           Afficher();
       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur:" + e.getMessage());
            e.printStackTrace();
        }
    }
  void Afficher() throws Exception{
          int x=Salle_Attente.tableRDV.getSelectedRow();
       TableModel model =Salle_Attente.tableRDV.getModel();
     String id= model.getValueAt(x, 5).toString();
     int code=Integer.parseInt(id);
     
     
     
     
      int consult=resultat1.tableC.getSelectedRow();
       TableModel model1 =resultat1.tableC.getModel();
     String id1= model1.getValueAt(consult, 0).toString();
     int code1=Integer.parseInt(id1);
//     
     
     
      System.out.println(code1);
       System.out.println(code);
         PreparedStatement p= c.prepareStatement("SELECT P.ID_PAT,P.NOM_PAT,P.PRENOM_PAT,P.AGE_PAT,P.ADRESSE_PAT,P.taille,P.poids,P.temperature,P.antecedents,P.SEXE_PAT,P.TEL_PAT,C.RESULTAT FROM PATIENT P,CONSULTATION C WHERE C.ID_PAT=P.ID_PAT AND P.ID_PAT=? and C.id_con=?");
         p.setInt(1, code);
         p.setInt(2, code1);
         ResultSet res=p.executeQuery();
         if(res.next()){
         idPat.setText(Integer.toString(res.getInt(1)));
         NomPat.setText(res.getString(2));
         PrenomPat.setText(res.getString(3));
         AgePat.setText(Integer.toString(res.getInt(4)));
         AdressePat.setText(res.getString(5));
         TaillePat.setText(Double.toString(res.getDouble(6)));
         PoidsPat.setText(Double.toString(res.getDouble(7)));
         temp.setText(Double.toString(res.getDouble(8)));
         ant.setText(res.getString(9));
         sexePat.setText(res.getString(10));
         TelPat.setText(res.getString(11));
         Resultat.setText(res.getString(12));
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        homebtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TelPat = new javax.swing.JTextField();
        idPat = new javax.swing.JTextField();
        NomPat = new javax.swing.JTextField();
        PrenomPat = new javax.swing.JTextField();
        AgePat = new javax.swing.JTextField();
        AdressePat = new javax.swing.JTextField();
        TaillePat = new javax.swing.JTextField();
        PoidsPat = new javax.swing.JTextField();
        temp = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        ant = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sexePat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Fiche Des Patients ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 30, 230, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Resultat Consultation :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));

        homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/home-_2_ (1).jpg"))); // NOI18N
        homebtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        jPanel1.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 50, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText(" ID Patient :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Nom Patient :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Prenom Patient :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("Age Patient :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("Adresse Patient :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel8.setText("Taille Patient :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel9.setText("Poids Patient :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setText("Temperature Patient :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setText("Antecedents :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        TelPat.setBackground(new java.awt.Color(204, 204, 255));
        TelPat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(TelPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 170, 20));

        idPat.setBackground(new java.awt.Color(204, 204, 255));
        idPat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(idPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 170, 20));

        NomPat.setBackground(new java.awt.Color(204, 204, 255));
        NomPat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(NomPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 170, 20));

        PrenomPat.setBackground(new java.awt.Color(204, 204, 255));
        PrenomPat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(PrenomPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 170, 20));

        AgePat.setBackground(new java.awt.Color(204, 204, 255));
        AgePat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(AgePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 170, 20));

        AdressePat.setBackground(new java.awt.Color(204, 204, 255));
        AdressePat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(AdressePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 170, 20));

        TaillePat.setBackground(new java.awt.Color(204, 204, 255));
        TaillePat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(TaillePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 170, 20));

        PoidsPat.setBackground(new java.awt.Color(204, 204, 255));
        PoidsPat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(PoidsPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 170, 20));

        temp.setBackground(new java.awt.Color(204, 204, 255));
        temp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 170, 20));

        jTextField12.setBackground(new java.awt.Color(204, 204, 255));
        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 170, 20));

        ant.setBackground(new java.awt.Color(204, 204, 255));
        ant.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ant, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 170, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setText("Sexe Patient :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        sexePat.setBackground(new java.awt.Color(204, 204, 255));
        sexePat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(sexePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 170, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel13.setText("Tel Patient :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        Resultat.setBackground(new java.awt.Color(204, 204, 255));
        Resultat.setColumns(20);
        Resultat.setRows(5);
        Resultat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(Resultat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
      resultat1 r= new resultat1();
        r.show();// TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_homebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FichePatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdressePat;
    private javax.swing.JTextField AgePat;
    private javax.swing.JTextField NomPat;
    private javax.swing.JTextField PoidsPat;
    private javax.swing.JTextField PrenomPat;
    private javax.swing.JTextArea Resultat;
    private javax.swing.JTextField TaillePat;
    private javax.swing.JTextField TelPat;
    private javax.swing.JTextField ant;
    private javax.swing.JButton homebtn;
    private javax.swing.JTextField idPat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField sexePat;
    private javax.swing.JTextField temp;
    // End of variables declaration//GEN-END:variables
}
