/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cabinetmedical;

import java.sql.*;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Modif_Patient extends javax.swing.JFrame {
Connection c;
    /**
     * Creates new form New_Patient
     */
    public Modif_Patient() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            try{
      //étape 1: charger la classe de driver
      Class.forName("com.mysql.cj.jdbc.Driver");
      //étape 2: créer l'objet de connexion
     c = DriverManager.getConnection(
      "jdbc:mysql://localhost:3306/Cabinet_medicale", "root", "");
          this.setLocationRelativeTo(null);
          this.setTitle("Modifier_Patient");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Erreur:"+e.getMessage());
        }
       
         this.setLocationRelativeTo(null);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        TelM = new javax.swing.JTextField();
        NomM = new javax.swing.JTextField();
        PrenomM = new javax.swing.JTextField();
        AgeM = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        GenreMo = new javax.swing.JRadioButton();
        GenreFM = new javax.swing.JRadioButton();
        AdresseM = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Tel  :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Nom  :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Prenom  :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Age  :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("Adresse  :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText("Sexe  :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Id:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        TelM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        jPanel1.add(TelM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 160, -1));

        NomM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        NomM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomMKeyPressed(evt);
            }
        });
        jPanel1.add(NomM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 200, -1));

        PrenomM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        PrenomM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PrenomMKeyPressed(evt);
            }
        });
        jPanel1.add(PrenomM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 200, 20));

        AgeM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        AgeM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AgeMKeyPressed(evt);
            }
        });
        jPanel1.add(AgeM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 200, -1));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        GenreMo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GenreMo.setText("M");
        jPanel1.add(GenreMo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        GenreFM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GenreFM.setText("F");
        jPanel1.add(GenreFM, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        AdresseM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        AdresseM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AdresseMKeyPressed(evt);
            }
        });
        jPanel1.add(AdresseM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 200, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 3, 24)); // NOI18N
        jLabel11.setText("Modification d'un Patient");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 300, -1));

        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/save-_1_ (1).jpg"))); // NOI18N
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 40, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/delete (1).jpg"))); // NOI18N
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 40, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/folder_add (1).jpg"))); // NOI18N
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 40, -1));

        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 320, 60));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 300, 10));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/ytytytyty.jpg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 310, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/kkkkkkkkkkkkkk.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//update patient
    void updatePatient(int id,String Name,String Prenom,int age,String Adresse,String Sexe,String Tel) throws Exception{
         PreparedStatement stm=c.prepareStatement("Update patient set NOM_PAT=?,PRENOM_PAT=?,AGE_PAT=?,ADRESSE_PAT=?,SEXE_PAT=?,TEL_PAT=? where id_pat=?");
         stm.setString(1, Name);
        stm.setString(2, Prenom);
        stm.setInt(3, age);
        stm.setString(4, Adresse);
        stm.setString(5, Sexe);
        stm.setString(6, Tel);
         stm.setInt(7, id);
        stm.executeUpdate();
    }






    private void NomMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomMKeyPressed
             char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            NomM.setEditable(true);
        }else{
             NomM.setEditable(false);
        }
    }//GEN-LAST:event_NomMKeyPressed

    private void PrenomMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrenomMKeyPressed
            char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            PrenomM.setEditable(true);
        }else{
             PrenomM.setEditable(false);
        }
    }//GEN-LAST:event_PrenomMKeyPressed

    private void AdresseMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdresseMKeyPressed
        // TODO add your handling code here:
             char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            AdresseM.setEditable(true);
        }else{
             AdresseM.setEditable(false);
        }
    }//GEN-LAST:event_AdresseMKeyPressed

    private void AgeMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgeMKeyPressed
             char c=evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)){
            AgeM.setEditable(true);
        }else{
             AgeM.setEditable(false);
        }
    }//GEN-LAST:event_AgeMKeyPressed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
         if(NomM.getText().equals("")||this.PrenomM.getText().equals("")||this.AdresseM.getText().equals("")||
              GenreMo.getText().equals("")||GenreFM.getText().equals("")||this.TelM.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Tout les Infos sont obligatoire !");
      }
         else{
               try{
        String id=this.id.getText();
        int idP=Integer.parseInt(id);
        String name=NomM.getText();
        String Prenom=this.PrenomM.getText();
        int age=Integer.parseInt(AgeM.getText());
        String Adresse=this.AdresseM.getText();
        String Sexe="";
        if(GenreMo.isSelected()){
            Sexe=GenreMo.getText();
        }
        if(GenreFM.isSelected()){
            Sexe=GenreFM.getText();
        }
      
        String Tel=this.TelM.getText();
       
                   updatePatient(idP, name, Prenom, age, Adresse, Sexe, Tel);
           
            JOptionPane.showMessageDialog(this,"Le patient est mis a jour  avec succés !");
     
 
        }catch(Exception e){
          JOptionPane.showMessageDialog(this,"Erreur:"+e.getMessage());
        }
      // dispose();
         }
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modif_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modif_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modif_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modif_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modif_Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField AdresseM;
    public javax.swing.JTextField AgeM;
    public javax.swing.JRadioButton GenreFM;
    public javax.swing.JRadioButton GenreMo;
    public javax.swing.JTextField NomM;
    public javax.swing.JTextField PrenomM;
    public javax.swing.JTextField TelM;
    private javax.swing.JButton Update;
    public javax.swing.JLabel id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
