/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cabinetmedical;

import java.sql.*;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class New_Patient extends javax.swing.JFrame {
Connection c;
    /**
     * Creates new form New_Patient
     */
    public New_Patient() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            try{
      //étape 1: charger la classe de driver
      Class.forName("com.mysql.cj.jdbc.Driver");
      //étape 2: créer l'objet de connexion
     c = DriverManager.getConnection(
      "jdbc:mysql://localhost:3306/Cabinet_medicale", "root", "");
                //System.out.println(c);
          this.setLocationRelativeTo(null);
          this.setTitle("Ajouter_Patient");
          
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Erreur:"+e.getMessage());
        }
       
         this.setLocationRelativeTo(null);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Tel = new javax.swing.JTextField();
        Nom = new javax.swing.JTextField();
        Prenom = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        GenreM = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        GenreF = new javax.swing.JRadioButton();
        Adresse = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ADDPATIENT = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Tel  :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Nom  :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Prenom  :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Age  :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("Adresse  :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText("Sexe  :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        Tel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        jPanel1.add(Tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 160, -1));

        Nom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        Nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomKeyPressed(evt);
            }
        });
        jPanel1.add(Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 200, -1));

        Prenom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        Prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrenomActionPerformed(evt);
            }
        });
        Prenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PrenomKeyPressed(evt);
            }
        });
        jPanel1.add(Prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 200, 20));

        Age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        Age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AgeKeyPressed(evt);
            }
        });
        jPanel1.add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 200, -1));

        GenreM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GenreM.setText("M");
        GenreM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenreMActionPerformed(evt);
            }
        });
        jPanel1.add(GenreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setText("+212");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        GenreF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GenreF.setText("F");
        jPanel1.add(GenreF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        Adresse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
        Adresse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AdresseKeyPressed(evt);
            }
        });
        jPanel1.add(Adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 200, -1));

        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 116, 320, 270));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 3, 24)); // NOI18N
        jLabel11.setText("Ajouter un Patient");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 210, -1));

        ADDPATIENT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/save-_1_ (1).jpg"))); // NOI18N
        ADDPATIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDPATIENTActionPerformed(evt);
            }
        });
        jPanel1.add(ADDPATIENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 40, -1));

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/delete (1).jpg"))); // NOI18N
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 40, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/folder_add (1).jpg"))); // NOI18N
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 40, -1));

        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 320, 60));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 153));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 300, 10));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/ytytytyty.jpg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 310, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/kkkkkkkkkkkkkk.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //ajouter_Patient
    void AjouterPatient(String Name,String Prenom,int age,String Adresse,String Sexe,String Tel) throws Exception{
        PreparedStatement stm=c.prepareStatement("Insert into patient(NOM_PAT,PRENOM_PAT,AGE_PAT,ADRESSE_PAT,SEXE_PAT,TEL_PAT,taille,poids,tension,temperature,antecedents) values(?,?,?,?,?,?,?,?,?,?,?)");
        stm.setString(1, Name);
        stm.setString(2, Prenom);
        stm.setInt(3, age);
        stm.setString(4, Adresse);
        stm.setString(5, Sexe);
        stm.setString(6, Tel);
        stm.setFloat(7, 0);
        stm.setFloat(8, 0);
        stm.setFloat(9, 0);
        stm.setFloat(10, 0);
         stm.setString(11, "");
        stm.executeUpdate();
       
    }
    private void NomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomKeyPressed
             char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            Nom.setEditable(true);
        }else{
             Nom.setEditable(false);
        }
    }//GEN-LAST:event_NomKeyPressed

    private void PrenomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrenomKeyPressed
            char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            Prenom.setEditable(true);
        }else{
             Prenom.setEditable(false);
        }
    }//GEN-LAST:event_PrenomKeyPressed

    private void AdresseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdresseKeyPressed
        // TODO add your handling code here:
             char c=evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            Adresse.setEditable(true);
        }else{
             Adresse.setEditable(false);
        }
    }//GEN-LAST:event_AdresseKeyPressed

    private void AgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgeKeyPressed
             char c=evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)){
            Age.setEditable(true);
        }else{
             Age.setEditable(false);
        }
    }//GEN-LAST:event_AgeKeyPressed

    private void PrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrenomActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        Nom.setText("");
                Prenom.setText("");
                Age.setText("");
                Adresse.setText("");
                Tel.setText("");
               GenreF.setText("");
               GenreM.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void ADDPATIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDPATIENTActionPerformed
  if(Nom.getText().equals("")||this.Prenom.getText().equals("")||this.Adresse.getText().equals("")||
              GenreM.getText().equals("")||GenreF.getText().equals("")||this.Tel.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Tout les Infos sont obligatoire !");
      }
      else{
        try{
        String name=Nom.getText();
        String Prenom=this.Prenom.getText();
        int age=Integer.parseInt(Age.getText());
        String Adresse=this.Adresse.getText();
        String Sexe="";
        if(GenreM.isSelected()){
            Sexe=GenreM.getText();
        }
        if(GenreF.isSelected()){
            Sexe=GenreF.getText();
        }
      
        String Tel="+212"+this.Tel.getText();
       
     
            AjouterPatient(name,Prenom,age,Adresse,Sexe,Tel);
            JOptionPane.showMessageDialog(this,"Le patient est ajouté avec succés !");
     
 
        }catch(Exception e){
          JOptionPane.showMessageDialog(this,"Erreur:"+e.getMessage());
        }
      }
      // dispose();
    }//GEN-LAST:event_ADDPATIENTActionPerformed

    private void GenreMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenreMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenreMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDPATIENT;
    private javax.swing.JTextField Adresse;
    private javax.swing.JTextField Age;
    private javax.swing.JRadioButton GenreF;
    private javax.swing.JRadioButton GenreM;
    private javax.swing.JTextField Nom;
    private javax.swing.JTextField Prenom;
    private javax.swing.JTextField Tel;
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
