/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cabinetmedical;

import java.io.IOException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Page_Acceuil extends javax.swing.JFrame {

    Connection c;

    /**
     * Creates new form Page_Acceuil
     */
    public Page_Acceuil() {
        initComponents();
        try {
            //étape 1: charger la classe de driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            //étape 2: créer l'objet de connexion
            c = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/Cabinet_medicale", "root", "");
            this.setLocationRelativeTo(null);
            this.setTitle("Accueil");
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            int x=Count();
            
jTextField4.setText("    "+Integer.toString(x)+"   ");
    int y=CountRDV();
            
jTextField6.setText("    "+Integer.toString(y)+"   ");
    int z=CountCons();
            
consultation.setText("    "+Integer.toString(z)+"   ");
DroitAcces();
DateHeure();


         //   System.out.println(MEDICAL.id);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur:" + e.getMessage());
        }

    }
    
    void DateHeure(){
       java.util.Date dd= new java.util.Date() ;
        SimpleDateFormat dat= new SimpleDateFormat("EEEE-dd-MMM-yyyy");
        SimpleDateFormat heur=new SimpleDateFormat("HH:mm");
        date.setText(dat.format(dd));
        heure.setText(heur.format(dd));
    }
    
      public static  void launch(){
                try {
       

            Runtime.getRuntime().exec("cmd /c start cmd.exe /K\" cd ../.. && cd .. && cd .. && cd .. && cd Users\\ACER\\anaconda3\\Lib\\site-packages\\bokeh\\sampledata\\_data && USHolidays.ics \"");
        } catch (IOException ex) {
          ex.printStackTrace();
        }
        }
    
    
    
    
    
    

    int Count() throws Exception {
        int count = 0;
        Statement stm = c.createStatement();
        ResultSet rs = stm.executeQuery("select count(*) as nbr from patient");
        if (rs.next()) {
            count = rs.getInt(1);
            //   System.err.println(count);
        }
     
        return count;
    }
    
    
    
     int CountRDV() throws Exception {
        int count = 0;
        Statement stm = c.createStatement();
        ResultSet rs = stm.executeQuery("select count(*) as nbr from rendez_vous where DATE_RDV=CURRENT_DATE");
        if (rs.next()) {
            count = rs.getInt(1);
            //   System.err.println(count);
        }
     
        return count;
    }

        int CountCons() throws Exception {
        int count = 0;
        Statement stm = c.createStatement();
        ResultSet rs = stm.executeQuery("select count(*) as nbr from consultation where DATE_CON=CURRENT_DATE");
        if (rs.next()) {
            count = rs.getInt(1);
            //   System.err.println(count);
        }
     
        return count;
    }
        
        
        
        void DroitAcces() throws Exception{
            PreparedStatement p=c.prepareStatement("select role from user where id_user=?");
            p.setInt(1, MEDICAL.id);
            ResultSet rs=p.executeQuery();
            if(rs.next()){
                String role=rs.getString(1);
              //  System.out.println(role);
                if(role.equals("MEDECIN")){
                    Gestion_Patients1.setVisible(false);
                    jLabel10.setVisible(false);
                    
                     RDV.setVisible(false);
                    jLabel6.setVisible(false);
                     
                    jLabel7.setVisible(false);
                     User.setVisible(false);
                   
                   // System.out.println("yes");
                }
                   if(role.equals("SECRETAIRE")){
                    jButton5.setVisible(false);
                    jLabel4.setVisible(false);
                    
                 
                   
                   // System.out.println("yes");
                }
                
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        consultation = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        User = new javax.swing.JButton();
        Agenda = new javax.swing.JButton();
        Gestion_Patients1 = new javax.swing.JButton();
        RDV = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Power = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        heure = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(0, 51, 204));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("  Consultations");
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 51, 204)));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setOpaque(true);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 90, 30));

        consultation.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        consultation.setForeground(new java.awt.Color(0, 51, 204));
        consultation.setText("     0");
        consultation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204), 2));
        consultation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultationActionPerformed(evt);
            }
        });
        jPanel1.add(consultation, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 90, 40));

        jTextField3.setBackground(new java.awt.Color(51, 204, 0));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("    Patients");
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 204, 0)));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 370, 90, 30));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(51, 204, 0));
        jTextField4.setText("    10");
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 0), 2));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 400, 90, 40));

        jTextField5.setBackground(new java.awt.Color(255, 0, 0));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("      RDV");
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 0)));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 90, 30));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 0, 0));
        jTextField6.setText("     0");
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 2));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 90, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/medecin2.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 120, 120));

        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/home-_1_ (1).jpg"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 60));

        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/male_user (1).jpg"))); // NOI18N
        User.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        jPanel1.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 100, 60));

        Agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/0ac2011a-c443-49d1-a568-4262f946 (1).jpg"))); // NOI18N
        Agenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendaActionPerformed(evt);
            }
        });
        jPanel1.add(Agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 100, 60));

        Gestion_Patients1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/male_user (1).jpg"))); // NOI18N
        Gestion_Patients1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Gestion_Patients1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gestion_Patients1ActionPerformed(evt);
            }
        });
        jPanel1.add(Gestion_Patients1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 100, 60));

        RDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/0ac2011a-c443-49d1-a568-4262f946 (1).jpg"))); // NOI18N
        RDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        RDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDVActionPerformed(evt);
            }
        });
        jPanel1.add(RDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 100, 60));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/c40a9e1f-308b-48f1-b49e-14ef0e05.jpg"))); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 100, 60));

        Power.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Documents\\NetBeansProjects\\projet_java\\src\\cabinetmedical\\bcdf71fb-e804-4cb9-ac4c-04b3a5d5.jpg")); // NOI18N
        Power.setActionCommand("");
        Power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerActionPerformed(evt);
            }
        });
        jPanel1.add(Power, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Accueil");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("USER");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 50, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Consultations");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 120, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Agenda");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setText("Patients");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText(" RDV");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 70, -1));

        date.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        date.setText("Le 2022-12-07");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 280, -1));

        heure.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        heure.setText("11:34:29");
        jPanel1.add(heure, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 80, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/[[[.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1020, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultationActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
      

    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        // TODO add your handling code here:
        Patients p=new Patients();
        p.show();
        dispose();
    }//GEN-LAST:event_UserActionPerformed

    private void AgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendaActionPerformed
        // TODO add your handling code here:
   launch();;
    }//GEN-LAST:event_AgendaActionPerformed

    private void Gestion_Patients1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gestion_Patients1ActionPerformed
      Gestion_User g= new Gestion_User();
      g.show();
      
      dispose();
    }//GEN-LAST:event_Gestion_Patients1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Salle_Attente s =new Salle_Attente();
       s.show();
       dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void RDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDVActionPerformed
        // TODO add your handling code here:
        Rendez_vous r= new Rendez_vous();
        r.show();
        dispose();
    }//GEN-LAST:event_RDVActionPerformed

    private void PowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerActionPerformed
        MEDICAL m=new MEDICAL();
        m.show();
        dispose();
    }//GEN-LAST:event_PowerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page_Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page_Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page_Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page_Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page_Acceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agenda;
    private javax.swing.JButton Gestion_Patients1;
    private javax.swing.JButton Power;
    private javax.swing.JButton RDV;
    private javax.swing.JButton User;
    private javax.swing.JTextField consultation;
    private javax.swing.JLabel date;
    private javax.swing.JLabel heure;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

}
