/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cabinetmedical;

import java.sql.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author HP
 */
public class Patients extends javax.swing.JFrame {
Connection c;
    /**
     * Creates new form Patients
     */
    public Patients() {
        initComponents();
       
             try{
      //étape 1: charger la classe de driver
      Class.forName("com.mysql.cj.jdbc.Driver");
      //étape 2: créer l'objet de connexion
     c = DriverManager.getConnection(
      "jdbc:mysql://localhost:3306/Cabinet_medicale", "root", "");
          this.setLocationRelativeTo(null);
          this.setTitle("Gestion Patients");
          afficherPatient();
         DateHeure();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Erreur "+e.getMessage());
        }
    }

        /** foction concerne les swing **/
      void afficherPatient() throws Exception {
           
           DefaultTableModel  m=new DefaultTableModel(null,
                   new String[]{"ID","NOM","Prenom","age","Adresse","Sexe","Tel"});
       
		Statement stmt =c.createStatement();
	ResultSet rslt=stmt.executeQuery("select * from patient order by id_pat ");
		
		while(rslt.next()) {
			m.addRow(new Object[]{rslt.getInt(1),rslt.getString(2),rslt.getString(3),
                            rslt.getInt(4),rslt.getString(5),rslt.getString(6),rslt.getString(7)});
		}
                tablePatient.setModel(m);
                
 //System.out.println(tablePatient);
               
    
       } 
        void DateHeure(){
       java.util.Date dd= new java.util.Date() ;
        SimpleDateFormat dat= new SimpleDateFormat("EEEE-dd-MMM-yyyy");
        SimpleDateFormat heur=new SimpleDateFormat("HH:mm");
        date.setText(dat.format(dd));
        heure.setText(heur.format(dd));
    }
    
    
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePatient = new javax.swing.JTable();
        searchText = new javax.swing.JTextField();
        heure = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        Adresse = new javax.swing.JLabel();
        Sexe = new javax.swing.JLabel();
        Tel = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        homebtn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/user_add (1).jpg"))); // NOI18N
        jButton1.setText("            New Patient");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 330, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel4.setText("ID  :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel5.setText("Nom  :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel6.setText("Prenom  :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/search (2).jpg"))); // NOI18N
        search.setBorder(null);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 30, 30));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel7.setText("Age  :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel8.setText("Adresse  :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel9.setText("Sexe  :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel11.setText("Tel  :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 330, 190));

        tablePatient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablePatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Prenom", "Age", "Adresse", "Sexe", "Tel"
            }
        ));
        tablePatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePatientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePatient);
        if (tablePatient.getColumnModel().getColumnCount() > 0) {
            tablePatient.getColumnModel().getColumn(0).setResizable(false);
            tablePatient.getColumnModel().getColumn(0).setPreferredWidth(2);
            tablePatient.getColumnModel().getColumn(3).setResizable(false);
            tablePatient.getColumnModel().getColumn(3).setPreferredWidth(2);
            tablePatient.getColumnModel().getColumn(5).setPreferredWidth(1);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 650, 160));

        searchText.setForeground(new java.awt.Color(153, 153, 153));
        searchText.setText("search by name");
        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });
        jPanel1.add(searchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 160, 30));

        heure.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        heure.setText("15:24:04");
        heure.setToolTipText("");
        jPanel1.add(heure, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, 20));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 60, 10));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 226, 70, 10));
        jPanel1.add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 246, 90, 10));
        jPanel1.add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 50, 10));
        jPanel1.add(Adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 150, 10));
        jPanel1.add(Sexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 50, 10));
        jPanel1.add(Tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 160, 10));

        date.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        date.setText("Le 2022-12-09");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 260, -1));

        jLabel17.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 255, 102));
        jLabel17.setText("Admin");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/user (1).jpg"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/home-_2_ (1).jpg"))); // NOI18N
        homebtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        jPanel1.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 50, 40));

        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 990, 60));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/delete (1).jpg"))); // NOI18N
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/notes_edit (1).jpg"))); // NOI18N
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        jPanel1.add(modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/refresh (1).jpg"))); // NOI18N
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel1.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 650, 60));

        jButton7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/ad7f0a75-4f73-46a2-9d10-fd19a9ad.jpg"))); // NOI18N
        jButton7.setText("           Informations Patients");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 330, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/qqqqq.jpg"))); // NOI18N
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 400, 190));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/background.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, -4, 1020, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextActionPerformed
 void SupprimerPatient(int numeroSelected) throws Exception {
		PreparedStatement stmt =c.prepareStatement("delete from Patient where id_pat=?");
		stmt.setInt(1,numeroSelected );

		 stmt.executeUpdate();
 }
 
 
 void Search(String name) throws Exception{
     int z=0;
     DefaultTableModel  m=new DefaultTableModel(null,
                   new String[]{"ID","NOM","Prenom","Age","Adresse","Sexe","Tel"});
     Statement stm=c.createStatement();
    
     
     ResultSet rslt=stm.executeQuery("select * from patient where NOM_PAT LIKE '%"+name+"%' ");
     while(rslt.next()) {
         z++;
         
			m.addRow(new Object[]{rslt.getInt(1),rslt.getString(2),rslt.getString(3),
                            rslt.getInt(4),rslt.getString(5),rslt.getString(6),rslt.getString(7)});
		}
    // System.out.println(z);
                tablePatient.setModel(m);
    
     
 }
        
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  New_Patient p= new New_Patient();
  p.show();
  
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablePatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePatientMouseClicked
       int x=tablePatient.getSelectedRow();
       TableModel model =tablePatient.getModel();
       id.setText(model.getValueAt(x, 0).toString());
       name.setText(model.getValueAt(x, 1).toString());
       prenom.setText(model.getValueAt(x, 2).toString());
       Age.setText(model.getValueAt(x, 3).toString());
       Adresse.setText(model.getValueAt(x, 4).toString());
       Sexe.setText(model.getValueAt(x, 5).toString());
       Tel.setText(model.getValueAt(x, 6).toString());
    }//GEN-LAST:event_tablePatientMouseClicked

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        try{
            afficherPatient();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erreur!");
        }
    }//GEN-LAST:event_RefreshActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
            //supprimer par selection
            Modif_Patient p=new Modif_Patient();
         
      int x= tablePatient.getSelectedRow();
     // System.out.println(x);
     if(x!=-1){
        
         int numeroSelectionner=(Integer)tablePatient.getValueAt(x, 0);
        // System.out.println(numeroSelectionner);
          try {
              p.show();
                PreparedStatement stm = c.prepareStatement("select * from patient where id_pat=?");
              stm.setInt(1, numeroSelectionner);
              ResultSet rs=stm.executeQuery();
              if(rs.next()){
               p.id.setText(Integer.toString(rs.getInt(1)));
              p.NomM.setText(rs.getString(2));
               p.PrenomM.setText(rs.getString(3));
                p.AgeM.setText(Integer.toString(rs.getInt(4)));
                 p.AdresseM.setText(rs.getString(5));
                  
                   p.TelM.setText(rs.getString(7));
              }
       
          } catch (Exception e) {
              JOptionPane.showMessageDialog(this, "Erreur !"+e.getMessage());
          }
         
     
      }else{
          JOptionPane.showMessageDialog(this, "Erreur  please select a Row !");
     }
        
     
        
    }//GEN-LAST:event_modifierActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
            //supprimer par selection
            int z=0;
      int []indices=  tablePatient.getSelectedRows();
     
     if(indices.length!=0){
          int x=JOptionPane.showConfirmDialog(this, "Etes vous sur de vouloir faire la suppression !");
         try{
             
         if(x==0){
      for(int i=0;i<indices.length;i++){
         int numeroSelectionner=(Integer)tablePatient.getValueAt(indices[i], 0);
          SupprimerPatient(numeroSelectionner);
          z++;
     
      }
         }
     
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, "erreur de saisie!");
            // e.printStackTrace();
        } 
         if(z==1){
              JOptionPane.showMessageDialog(this, "Patient a été supprimé !");
         }
         if(z>1){
              JOptionPane.showMessageDialog(this, "Patients ont été supprimé !");
         }
     }else{
          JOptionPane.showMessageDialog(this, "Erreur  please select a Row !");
     }

    }//GEN-LAST:event_deleteActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
       String name= searchText.getText();
    try {
        
        Search(name);
    } catch (Exception e) {
       JOptionPane.showMessageDialog(this, "Erreur !"+e.getMessage());
    }
    }//GEN-LAST:event_searchActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
Page_Acceuil p=new Page_Acceuil();
p.show();// TODO add your handling code here:
dispose();
    }//GEN-LAST:event_homebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adresse;
    private javax.swing.JLabel Age;
    private javax.swing.JButton Refresh;
    private javax.swing.JLabel Sexe;
    private javax.swing.JLabel Tel;
    private javax.swing.JLabel date;
    private javax.swing.JButton delete;
    private javax.swing.JLabel heure;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifier;
    private javax.swing.JLabel name;
    private javax.swing.JLabel prenom;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchText;
    private javax.swing.JTable tablePatient;
    // End of variables declaration//GEN-END:variables

    

    
}
