/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cabinetmedical;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Prescriptions extends javax.swing.JFrame {
    Connection c;
    /**
     * Creates new form Prescriptions
     */
    public Prescriptions() {
        initComponents();
        try {
            //étape 1: charger la classe de driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            //étape 2: créer l'objet de connexion
            c = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/Cabinet_medicale", "root", "");
           AfficherIDOR();
           AfficherIDMED();
           this.setTitle("Prescriptions");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur:" + e.getMessage());
        }
          setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
          this.setLocationRelativeTo(null);
    }

    void Ajouter(int idOr,int idMedcm,int Quantite,int duree) throws Exception{
        PreparedStatement p=c.prepareStatement("insert into prescrire values(?,?,?,?)");
        p.setInt(1, idOr);
          p.setInt(2, idMedcm);
            p.setInt(3, Quantite);
              p.setInt(4, duree);
              p.executeUpdate();
    }
    
    void AfficherIDOR() {
        try{
        id_Ord.removeAllItems();
        Statement s=c.createStatement();
        ResultSet res=s.executeQuery("select id_ord from ordonnance");
        while(res.next()){
           int idOrd=res.getInt(1);
            String idO=  Integer.toString(idOrd);
            id_Ord.addItem(idO);
            
        }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
       void AfficherIDMED() {
        try{
        id_Med.removeAllItems();
        Statement s=c.createStatement();
        ResultSet res=s.executeQuery("select id_medm,nom_medm from medicaments");
        while(res.next()){
           int idOrd=res.getInt(1);
           String nom=res.getString(2);
            String idO=  Integer.toString(idOrd)+"-"+nom;
            id_Med.addItem(idO);
        }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id_Ord = new javax.swing.JComboBox<>();
        id_Med = new javax.swing.JComboBox<>();
        duree = new javax.swing.JTextField();
        qte = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Duree :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("ID_Ord : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("ID_Medm :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("Quantite :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        id_Ord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(id_Ord, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 150, 30));

        id_Med.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(id_Med, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 150, 30));

        duree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        duree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dureeActionPerformed(evt);
            }
        });
        duree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dureeKeyPressed(evt);
            }
        });
        jPanel1.add(duree, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 150, 30));

        qte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        qte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qteActionPerformed(evt);
            }
        });
        qte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qteKeyPressed(evt);
            }
        });
        jPanel1.add(qte, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 150, 30));

        save.setBackground(new java.awt.Color(153, 204, 255));
        save.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        save.setText(" Save ");
        save.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 100, 40));

        cancel.setBackground(new java.awt.Color(255, 102, 102));
        cancel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cancel.setText("Cancel ");
        cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 100, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/3595970.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
     
        String str=id_Ord.getSelectedItem().toString();
         String str1=id_Med.getSelectedItem().toString();
         String s=str1.substring(0, 1);
         
         int idO=Integer.parseInt(str);
         int idM=Integer.parseInt(s);
         if(qte.getText().equals("")||duree.getText().equals("")){
             JOptionPane.showMessageDialog(this, "Toutes les infos sont obligatoires ");
         }
         else{
             try{
             int qte=Integer.parseInt(this.qte.getText());
             int duree=Integer.parseInt(this.duree.getText());
                 Ajouter(idO, idM, qte, duree);
                  JOptionPane.showMessageDialog(this, "Ajout avec succes !");
             }catch(Exception e){
                 JOptionPane.showMessageDialog(this, "Erreur "+e.getMessage());
             }
         }
        
        
        
    }//GEN-LAST:event_saveActionPerformed

    private void dureeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dureeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dureeActionPerformed

    private void qteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qteActionPerformed

    private void qteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qteKeyPressed

 char c=evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)){
            qte.setEditable(true);
        }else{
             qte.setEditable(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_qteKeyPressed

    private void dureeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dureeKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)){
            duree.setEditable(true);
        }else{
             duree.setEditable(false);
        }
    }//GEN-LAST:event_dureeKeyPressed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        qte.setText("");
        duree.setText("");
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prescriptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prescriptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prescriptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prescriptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prescriptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField duree;
    private javax.swing.JComboBox<String> id_Med;
    private javax.swing.JComboBox<String> id_Ord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField qte;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
