/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cabinetmedical;

import java.sql.*;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Rendez_vous extends javax.swing.JFrame {
   Connection c;
    /**
     * Creates new form Rendez_vous
     */
    public Rendez_vous() {
        initComponents();
        try {
            //étape 1: charger la classe de driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            //étape 2: créer l'objet de connexion
            c = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/Cabinet_medicale", "root", "");
         // System.out.println(c);
         this.setTitle("Rendez_Vous");
           afficherRDV();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur:" + e.getMessage());
           // e.printStackTrace();
        }
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddRDV = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Annuler = new button.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRDV = new javax.swing.JTable();
        deleteRDV = new javax.swing.JButton();
        attente = new button.Button();
        confirmer = new button.Button();
        Accueil = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddRDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/8a79e246-fca4-4202-a96d-6a243960.jpg"))); // NOI18N
        AddRDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRDVActionPerformed(evt);
            }
        });
        jPanel1.add(AddRDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 40, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/printer (1).jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 40, 40));

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/refresh (1).jpg"))); // NOI18N
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel1.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Le 2022-12-15");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 130, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("10:27:57");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 60, 70, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Total : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 60, 70, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("3");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 20, 20));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 850, 70));

        Annuler.setBackground(new java.awt.Color(253, 83, 83));
        Annuler.setForeground(new java.awt.Color(245, 245, 245));
        Annuler.setText("Annuler");
        Annuler.setRippleColor(new java.awt.Color(255, 255, 255));
        Annuler.setShadowColor(new java.awt.Color(253, 83, 83));
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(Annuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 80, -1));

        tableRDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Prenom", "Nom", "Date_Present", "Heure_Present", "Remarque", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableRDV);
        if (tableRDV.getColumnModel().getColumnCount() > 0) {
            tableRDV.getColumnModel().getColumn(0).setPreferredWidth(2);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 640, 360));

        deleteRDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/delete (1).jpg"))); // NOI18N
        deleteRDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRDVActionPerformed(evt);
            }
        });
        jPanel1.add(deleteRDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 40, 40));

        attente.setBackground(new java.awt.Color(29, 162, 253));
        attente.setForeground(new java.awt.Color(245, 245, 245));
        attente.setText("attente");
        attente.setRippleColor(new java.awt.Color(255, 255, 255));
        attente.setShadowColor(new java.awt.Color(29, 162, 253));
        attente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attenteActionPerformed(evt);
            }
        });
        jPanel1.add(attente, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 80, -1));

        confirmer.setBackground(new java.awt.Color(30, 180, 114));
        confirmer.setForeground(new java.awt.Color(245, 245, 245));
        confirmer.setText("confirmer");
        confirmer.setRippleColor(new java.awt.Color(255, 255, 255));
        confirmer.setShadowColor(new java.awt.Color(30, 180, 114));
        confirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmerActionPerformed(evt);
            }
        });
        jPanel1.add(confirmer, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 80, -1));

        Accueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/home-_2_ (1).jpg"))); // NOI18N
        Accueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccueilActionPerformed(evt);
            }
        });
        jPanel1.add(Accueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 44, 50, -1));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 160, 160));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/sec (1).jpg"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 200, 130));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Status");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 90, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmedical/background.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 880, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

      void afficherRDV() throws Exception {
          
           DefaultTableModel  z=new DefaultTableModel(null,
                   new String[]{"ID_RDV","Prenom","Nom","Date_Present","Heure_Present","Remarque","Status"});
       
		Statement stmt =c.createStatement();
	ResultSet rslt=stmt.executeQuery("select r.id_rdv,p.prenom_pat,p.nom_pat,r.date_rdv,r.heure_rdv,r.remarque,r.etat from patient p, rendez_vous r where p.id_pat=r.id_pat");
		//ResultSet rslt=stmt.executeQuery("select * from rendez_vous");
		while(rslt.next()) {
                   int id=rslt.getInt(1);
                    
                   String prenom=rslt.getString(2);
                   String nom=rslt.getString(3);
                   Date d=rslt.getDate(4);
                   String heure=rslt.getString(5);
                   String remarque=rslt.getString(6);
                   String status=rslt.getString(7);
                   // System.out.println(remarque);
	z.addRow(new Object[]{id,prenom,nom,d,heure,remarque,status});
                      
		}
               
               
                tableRDV.setModel(z);
               // System.out.println(tableRDV);
                

               
    
       } 
    
    void SupprimerRDV(int numeroSelected) throws Exception {
		PreparedStatement stmt =c.prepareStatement("delete from rendez_vous where id_rdv=?");
		stmt.setInt(1,numeroSelected );

		 stmt.executeUpdate();
 }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AddRDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRDVActionPerformed
        // TODO add your handling code here:
       Ajouter_RDV r=new Ajouter_RDV();
        r.show();
    }//GEN-LAST:event_AddRDVActionPerformed

    private void AccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccueilActionPerformed

Page_Acceuil p=new Page_Acceuil();
p.show();// TODO add your handling code here:
dispose();
    }//GEN-LAST:event_AccueilActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
   try{
            afficherRDV();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erreur!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void deleteRDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRDVActionPerformed
           //supprimer par selection
            int z=0;
      int []indices=  tableRDV.getSelectedRows();
     
     if(indices.length!=0){
          int x=JOptionPane.showConfirmDialog(this, "Etes vous sur de vouloir faire la suppression !");
         try{
             
         if(x==0){
      for(int i=0;i<indices.length;i++){
         int numeroSelectionner=(Integer)tableRDV.getValueAt(indices[i], 0);
          SupprimerRDV(numeroSelectionner);
          z++;
     
      }
         }
     
        }catch(Exception e){
             JOptionPane.showMessageDialog(this, "erreur de saisie!");
             e.printStackTrace();
        } 
         if(z==1){
              JOptionPane.showMessageDialog(this, "Rendez vous a été supprimé !");
         }
         if(z>1){
              JOptionPane.showMessageDialog(this, " Rendez vous ont été supprimé !");
         }
     }else{
          JOptionPane.showMessageDialog(this, "Erreur  please select a Row !");
     }
    }//GEN-LAST:event_deleteRDVActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
       int x= tableRDV.getSelectedRow();
    
     if(x!=-1){
        
         int numeroSelectionner=(Integer)tableRDV.getValueAt(x, 0);
        // System.out.println(numeroSelectionner);
          try {
              //p.show();
                PreparedStatement stm = c.prepareStatement("update rendez_vous set etat='Annuler' where id_rdv=?");
              stm.setInt(1, numeroSelectionner);
            stm.executeUpdate();
            afficherRDV();
       
          } catch (Exception e) {
              JOptionPane.showMessageDialog(this, "Erreur !"+e.getMessage());
          }
         
     
      }else{
          JOptionPane.showMessageDialog(this, "Erreur  please select a Row !");
     }    
    }//GEN-LAST:event_AnnulerActionPerformed

    private void attenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attenteActionPerformed
      int x= tableRDV.getSelectedRow();
    
     if(x!=-1){
        
         int numeroSelectionner=(Integer)tableRDV.getValueAt(x, 0);
        // System.out.println(numeroSelectionner);
          try {
              //p.show();
                PreparedStatement stm = c.prepareStatement("update rendez_vous set etat='attente' where id_rdv=?");
              stm.setInt(1, numeroSelectionner);
            stm.executeUpdate();
            afficherRDV();
       
          } catch (Exception e) {
              JOptionPane.showMessageDialog(this, "Erreur !"+e.getMessage());
          }
         
     
      }else{
          JOptionPane.showMessageDialog(this, "Erreur  please select a Row !");
     }    
    }//GEN-LAST:event_attenteActionPerformed

    private void confirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmerActionPerformed
  int x= tableRDV.getSelectedRow();
    
     if(x!=-1){
        
         int numeroSelectionner=(Integer)tableRDV.getValueAt(x, 0);
        // System.out.println(numeroSelectionner);
          try {
              //p.show();
                PreparedStatement stm = c.prepareStatement("update rendez_vous set etat='confirmer' where id_rdv=?");
              stm.setInt(1, numeroSelectionner);
            stm.executeUpdate();
            afficherRDV();
       
          } catch (Exception e) {
              JOptionPane.showMessageDialog(this, "Erreur !"+e.getMessage());
          }
         
     
      }else{
          JOptionPane.showMessageDialog(this, "Erreur  please select a Row !");
     }        // TODO add your handling code here:
    }//GEN-LAST:event_confirmerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rendez_vous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rendez_vous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rendez_vous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rendez_vous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rendez_vous().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accueil;
    private javax.swing.JButton AddRDV;
    private button.Button Annuler;
    private button.Button attente;
    private button.Button confirmer;
    private javax.swing.JButton deleteRDV;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refresh;
    private javax.swing.JTable tableRDV;
    // End of variables declaration//GEN-END:variables
}
